version: "3"
services:
  db: # 서비스 명
    container_name: "db"
    image: mysql # 사용할 이미지
    restart: always
    # ports: #컨테이너에서만 접근할 수 있도록 주석처리
    #   - "3307:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "0000"
      MYSQL_DATABASE: "animationtool"
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/dbdata:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    networks:
      - local-net
  api:
    links:
      - db
    build: ./api
    env_file:
      - api/.env
    ports:
      - "5000:5000"
    networks:
      - local-net
networks:
  local-net:
    driver: bridge
