"""add column

Revision ID: a02332314dc8
Revises: a9bda8d60757
Create Date: 2021-10-02 22:21:46.717839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02332314dc8'
down_revision = 'a9bda8d60757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
